// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial3_Web.Data;

#nullable disable

namespace Parcial3_Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251112180431_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Parcial3_Web.Models.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contactos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Departamento = "Ventas",
                            Email = "juan@email.com",
                            FechaCreacion = new DateTime(2025, 11, 12, 12, 4, 31, 343, DateTimeKind.Local).AddTicks(3198),
                            Nombre = "Juan Pérez",
                            Telefono = "555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Departamento = "Soporte",
                            Email = "maria@email.com",
                            FechaCreacion = new DateTime(2025, 11, 12, 12, 4, 31, 343, DateTimeKind.Local).AddTicks(3201),
                            Nombre = "María García",
                            Telefono = "555-0102"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Departamento = "IT",
                            Email = "carlos@email.com",
                            FechaCreacion = new DateTime(2025, 11, 12, 12, 4, 31, 343, DateTimeKind.Local).AddTicks(3203),
                            Nombre = "Carlos López",
                            Telefono = "555-0103"
                        });
                });

            modelBuilder.Entity("Parcial3_Web.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 11, 12, 12, 4, 31, 343, DateTimeKind.Local).AddTicks(3013),
                            NombreCompleto = "Administrador del Sistema",
                            NombreUsuario = "admin",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 11, 12, 12, 4, 31, 343, DateTimeKind.Local).AddTicks(3017),
                            NombreCompleto = "Usuario Demo",
                            NombreUsuario = "usuario",
                            Password = "password"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 11, 12, 12, 4, 31, 343, DateTimeKind.Local).AddTicks(3019),
                            NombreCompleto = "Usuario de Demo",
                            NombreUsuario = "demo",
                            Password = "demo123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
